_target_: bms.model.egnn.EGNN_dynamics
n_particles: ${num_atoms}
spatial_dim: ${spatial_dim}
hidden_nf: 128
n_layers: 5
act_fn:
  _target_: torch.nn.SiLU
recurrent: true
tanh: true
attention: true
condition_time: true
agg: sum
